# Generated by Django 5.1.6 on 2025-02-21 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medspas', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('total_duration', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('medspa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medspas.medspamodel')),
                ('services', models.ManyToManyField(to='services.servicemodel')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
