# Generated by Django 5.1.6 on 2025-02-22 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='total_duration',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='total_price',
        ),
    ]
