# Generated by Django 5.1.6 on 2025-02-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointmentmodel_total_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='total_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
