# Generated by Django 5.1.6 on 2025-02-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointmentmodel_total_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Scheduled', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='total_duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
